name: Pull request

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::668387820763:role/aws-iam-scanner

      - name: Run script
        # Second and fourth account taken from https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-api-with-vpclink-accounts.html
        run: yarn start --principals 111122223333 392220576650 444455556666 718770453195
